name    'reppard-jdk8'
version '0.0.4'
source  'https://github.com/reppard/puppet-jdk8'
author 'reppard'
license 'Apache License, Version 2.0'
summary 'Oracle JDK 8 for RH/CentOS'
description 'See summary'
project_page  'https://github.com/reppard/puppet-jdk8'
